### PR TITLE
improve echocolor handling

### PR DESCRIPTION
**Pull request by maghuro**
everything inside a function - futureproof

### CODE REVIEW

**Comment by dave14305** [comment]
I prefer the simplicity of Red/Yellow/Green/Blue. This takes up more space every time you want to echo something in color.

**Comment by maghuro** [comment]
I understand sir :)

**Comment by maghuro** [comment]
You can try this way. It's your call :)

**Comment by dave14305** [comment]
I appreciate the ideas, but I will keep it simple and easier for me to read in the code.

**Comment by maghuro** [comment]
That's ok pal, you're in charge :)

**Pull request closed without merging**
