### PR TITLE
Develop - Add duplicate removal in Connection Tracking and update Bandwidth table

### PR DESCRIPTION
**Pull request by Lacrocious**
Hi Dave,
Here is my attempt at removing duplicates in the Connection Tracking table as well as tweaks to the Bandwidth table.  

For Connection Tracking - the Local Port will hold either the Local Port Number for single entries or "x DUPS" where "x" is the count of duplicates.  The Tool Tip will contain the list of ports that were found to be duplicates.

For the Bandwidth table, I mimic'ed your other tables with the colored box around the Class name and eliminated your colored borders.  I see you made some other updates to Develop, but I have not pulled them in and looked at them.  

See if you like what I did for either or both.  Also, let me know how the fork + pull request works out as it is my first time working with GitHub.
 - Lacrocious/Ron

### CODE REVIEW

**Comment by dave14305** [comment]
My first preference is to avoid pushing the row onto the tabledata array in the first place. Your approach filters on drawing the table at the end. I have some doubts about its effectiveness (without trying it yet myself) because you’re only looking back at the previous row and in my experience you can’t really rely on the table being sorted in any particular order besides App name and local IP. What did you see in your tests?

I haven’t had morning coffee yet, so I may be missing the nuance.

**Comment by Lacrocious** [comment]
Interesting - you can sort by selecting the headers!  I hadn't recognized that option.  You are right, filtering on the output will only remove duplicates that are sorted together.  It won't break things, but it wouldn't remove duplicates as they wouldn't be next to each other.    I looked a little at the creation of the tabledata, then found the creation of the HTML Table and thought that would be easy.  It was, but wouldn't work in all cases.  I'll look again at the creation of tabledata.

**Comment by Lacrocious** [comment]
Dave,
Take another look.  I stepped back to your latest DEV build with the updated Bandwidth table and removed my Bandwidth table for now, focusing on the De-Dup.  The dedup now works in draw_conntrack_table.  After your filtering eliminates entries, it checks to see if the item already exists in datatable.  If it doesn't exist, it adds to datable per normal.  If it finds an entry that matches all values except local port, it does not add that item.  The local port for the item already in the table is appended with the port for the current item so that we can still build the tool-tip to the local port to include all local ports that are duplicates.  

I did tweak the UpdateTable routine to set the LocalPort to either the real, local port for an entry without duplicates or to the word "DUPs" if there were duplicates.  In all cases, the Tool Tip contains the list of local ports.

Let me know what you think.

**Comment by dave14305** [comment]
I'd be afraid that this would take a long time to process since for every row, we scan the array (which keeps growing anyway). It might perform OK for a certain number of connections, but when you get over 500 or over 750, each loop will take longer and longer.

But this is definitely forcing me to think about it from other angles I hadn't considered before, so we're making progress. Performance is key for this table since we already have to search through every rule for every connection, so adding another lengthy loop is risky.

**Comment by Lacrocious** [comment]
I agree - performance is key.  What I wrote definitely gets less efficient the more rows that get added to datable.  You have a limit of 500 on the datatable, so I definately it would be worth a try.  I believe it works, but efficiency may not be enough.  

I did think of an alternate way that may be faster to process, but would require some testing.  If we step back to the original draw_conntrack_table, we could call a de-dup function just before calling updatetable.  If we can sort datatable by Source IP by Dest IP by Port - we can step through the table the way I originally did in updatetable, but knowing we have everything in the proper order to step through without stepping through the table like I just did.  I didn't go there because I don't know a good, built-in three-level sort of an array.  Do you know of a multi-level sort w/o re-implementing the wheel?

I'm thinking we could do something similar to how you are treating the Class Priority.  When datatable is built in draw_conntrack_table, we could build a temp array rather than datatable and update Source IP to be "SourceIP:RemoteIP:RemotePort".  This allows us to do a single-level sort on Source IP (Source IP:Remote IP:RemotePort), putting datatable into an order we can step through w/o lookups.  Then we walk through the temp table, eliminating duplicates and restore SourceIP by trimming off the added bits.  It is a single sort, then walk the table.  

I can give this a try tomorrow.  I expect it will be faster than the last iteration.  Do you have other thoughts before I dive into more code?

**Comment by Lacrocious** [comment]
Say - do you agree we only need to compare Protocol, SourceIP, Dest IP and Dest Port?  I have been comparing everything, but I think that is overkill.  There shouldn't be a need to compare Title, Traffic ID, or Category - they should match anyway.  Thoughts?

**Comment by dave14305** [comment]
> Say - do you agree we only need to compare Protocol, SourceIP, Dest IP and Dest Port? I have been comparing everything, but I think that is overkill. There shouldn't be a need to compare Title, Traffic ID, or Category - they should match anyway. Thoughts?

I believe we need to compare everything, in the possible scenario that an iptables rule that includes local port (e.g. FaceTime) could result in a different Application name and priority. We don’t want to hide those exceptions.

**Comment by Lacrocious** [comment]
OK - Comparing everything.  I have another version that is working that does the processing discussed above.  I am collecting statistics, but the initial version with the lookup in tabledata is much more efficient.  All the string processing (concatenation and splitting) is intensive and I am sure memory usage is increased because you will need a 3rd copy of the data for at least part of the time.    I will try to capture some logging using both methods under similar loading to be able to better determine impact.  On first blush, the first version has minimal time impact of a few ms, while the second version has a much greater impact in the range of 8-14ms.

Time to review the code again and collect some statistics.

**Comment by Lacrocious** [comment]
Hi Dave,
I just wanted to give you an update.  I have been testing a few different builds and reviewing processing stats.    I’ll send more info and stats this coming weekend, but I have an implementation that adds only a 1-3 milliseconds and properly de-dupes the table.  I have a build that actually generates statistics and the table for 3 different versions, including the current, non-deduped version.  I have confirmed the de-duplication by copying the table for the 3 different processes out of the web page into Excel and reviewing/comparing data.  I’ll get that both versions committed here so you can review if you like as well as putting together a version with just the “fastest” processing.  
- L

**Comment by Lacrocious** [comment]
Hi Dave,
I pushed 2 updates.  The first update generates the 3 styles of output and shows them all on the web page and outputs statistics to the web console in your browser.  This allowed me to copy the generated HTML table to Excel and perform comparisons to ensure the data is all accounted for.  The 3 styles are:
V0:  Original routines to build the the tabledata from the comm_tracks and generate the web page table.
V1:  As the routine adds rows to tabledata, it checks to see if the current data matches a row that already exists and skips adding duplicates.
V2:  After the rote adds rows to a temp tabledata, it sorts and removes duplicates, then builds tabledata and generates the web page table.  I have noticed that in some cases, the sorting does not properly sort and thus there are some duplicates that are not properly identified as they are not grouped together.  Due to the speed issues with this scenario, I have not dug deeper into the sorting issue.

What I learned is that the the string processing to build temp tables is very costly to processing.  This means that ‘updateTable’ is the slowest portion of the processing.  Additionally, building the temporary lookup table for V2 is extremely costly.   V1 ends up being faster, potentially faster than the original (V0) processing for larger numbers of connections because of the fewer rows that end up being processed into HTML via slow string concatenation.

In my testing, I increased the row limit from 500 to 1500 to have better statistics.    In the tables below, you can see that V0 Draw_ConnTrack_Table is faster than V1, but results in a larger number of rows passed to UpdateTable.  The larger number of rows passed to UpdateTable results in longer processing time for V0 vs. V1 and the smaller row count.  V2 is just too slow and it also has an occasional issue sorting the data properly to allow stepping through the table rather than using lookups to de-duplicate.  

The statistics also show time vs row count passed to UpdateTable is not linear, rather exponentially increasing time with row count.  The string manipulation Is affecting the processing time greatly.  When all is said and done, the deduplication of V1 results in similar or faster processing times as the original processing, depending on the row count passed to UpdateTable.   The lower the row count, the faster the HTML build processing.  I think we have a good option here such that you could potentially increase the limit from 500 to 1000 without real time impact and the ability to give people view of more connections.

I know this is long - but put the debug version online and watch your connections and look at your browser console log for the counts.  I will start building the streamlined version without the debugging code and post that.

The second update incorporates your latest changes from DEV as well as implements the V1 de-duplication described above.  All browser console logging has been commented out.  The Max tracked connections is back to your defaults of 500.  Overall, they run quicker than we both initially expected, so I am glad I dug into the statistics of the timings and didn't rely on both our expectations that the lookup table would be slow.

Give them a try and let me know your thoughts on the above and the code.  Thanks!
 - L

Example Statistics:
Connection Count:  1902	Max Connections:  1500
Type:	Draw_ConnTrack_Table	UpdateTable	Total Time	Final Row Count
V0		11ms					119ms		130ms		1500
V1		17ms					33ms		50ms		989
V2		345ms					36ms		381ms		823

Connection Count:  662		Max Connections:  1500
Type:	Draw_ConnTrack_Table	UpdateTable	Total Time	Final Row Count
V0		2ms						45ms		47ms		662
V1		5ms						8ms			15ms		328
V2		22ms					8ms			30ms		334

Connection Count:  665		Max Connections:  1500
Type:	Draw_ConnTrack_Table	UpdateTable	Total Time	Final Row Count
V0		3ms						46ms		49ms		665
V1		2ms						9ms			11ms		329
V2		55ms					10ms		65ms		335

**Comment by dave14305** [comment]
Thanks for trying. Closing due to project winddown.

**Pull request closed without merging**
